---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: api-keptn-ingress
  namespace: keptn
spec:
  rules:
  - host: domain.placeholder.nip.io
    http:
      paths:
      - path: /
        backend:
          service:           
            name: api-gateway-nginx
            port: 80