apiVersion: "spec.keptn.sh/0.2.3"
kind: "Shipyard"
metadata:
  name: "shipyard-performance"
spec:
  stages:
    - name: "quality-gate"
      sequences:
        - name: "delivery"
          tasks:
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"