apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public-gateway
  namespace: istio-system
spec:
  selector:
    app: public-gateway-ingress
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - '*'
