---
apiVersion: v1
kind: Service
metadata: 
  name: keptnwebservice
  labels: 
    app: keptnwebservice
spec: 
  type: {{ .Values.service.type }}
  ports: 
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPport }}
  selector: 
    app: keptnwebservice
